# Generated by Django 5.0.7 on 2024-07-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_anuncio_imagen_alter_anuncio_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='./'),
        ),
    ]
